### PR TITLE
Added Kicad footprints

### PR DESCRIPTION
**Pull request by Junes-PhD**
Added multiple sizes of Kicad footprints.  Mono and dual colors.

### CODE REVIEW

**Comment by jywarren** [comment]
Very cool and thanks for the PR! I don't have Kicad experience; could you provide a screenshot of the templates open in the interface?

**Comment by Junes-PhD** [comment]
mono screen cap
dual screen cap

**Comment by Junes-PhD** [comment]
All files were made with svg2mod, so they should look good at all sizes. 
https://github.com/mtl/svg2mod

scale render
scale board

**Comment by jywarren** [comment]
Perfect then, thanks!

**Comment by jywarren** [comment]
Excellent - what are your thoughts on the size/readability of the unique
code -- I'm not familiar with Kicad scale management. Otherwise this looks
good to go!

**Comment by Junes-PhD** [comment]
I thought it would be best done with the built in text feature.   The logo has to be a static file, so to my knowledge, you can't add variable text. The steps would be load in logo and then add in a text string with the country code and id.  When I get some more time I will add recommendations for offsets and font size based on the master svg file.   This will take the guess work out of alignments and sizes.  If I lay a kicad text string of "w35bir" over the svg "w35bir", I should be able to get the size and positioning close to the standard.  The variables I can play with are shown below.  
text

**Comment by jywarren** [comment]
Oh, this sounds awesome, thanks.

**Pull request merged**
