### PR TITLE
Kicad - Added Text Field

### PR DESCRIPTION
**Pull request by Junes-PhD**
Added Text field to Kicad footprints.
I released it was possible and updated with the changeable 2 Character country code and 5 digital I.D.
Text size was determined visually and then mathematically scaled for relative symmetry,

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, thank you -- can you share a screenshot example so we can take a look before merging? Thank you very much!

**Comment by Junes-PhD** [comment]
capture

**Comment by jywarren** [comment]
This looks good -- do you thikn you could double the space between the code and the box, and make the numbers about 5% smaller? 

image

**Comment by Junes-PhD** [comment]
I am not sure of the best way to describe changes so I threw in a few options.  Once we get a size I will redo the rest of them.


Double Space 5% Smaller
double space 5

Double Space 10% Smaller 30% Thinner
double space 10 smaller 30 thiner

Double Space 15% Smaller 30% Thinner
double space 15 smaller 30 thiner

**Comment by jywarren** [comment]
Great -- i think "Double Space 5% Smaller" is the best combination of readability and clean aesthetics, thank you!

**Comment by Junes-PhD** [comment]
Changes pushed

**Comment by jywarren** [comment]
Ready for merge?

**Comment by Junes-PhD** [comment]
Yes.

**Comment by jywarren** [comment]
Thank you, excellent!

**Pull request merged**
